import type { Metadata } from "next";
import "./globals.css";
import styles from "./layout.module.css";
import { Header } from "@/components/header/header";
import Providers from "./providers";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const robotoCondensed = localFont({
  src: "./fonts/Roboto_Condensed/RobotoCondensed-VariableFont_wght.ttf",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={robotoCondensed.className}>
      <body className={styles.body}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
